### ISSUE TITLE
Running start_client.sh  in blockbench/benchmark/parity

### ISSUE THREAD

**Issue by xiaohua0921** [ooibc88/blockbench#16]
I want  to run start_client.sh in the directory of blockbench/benchmark/parity/  , there have "nohup ../../src/ycsb/driver -db parity -threads $THREADS -P ../../src/ycsb/workloads/workloada.spec -endpoint $HOST -txrate $RATE > $LOG 2>&1 &"  in the file ,but in the code that I download , don't have the ycsb directory ,only have src/macro/kvstore and src/macro/smallbank , do I need download other code in somewhere ??? Or install other things？？

**Comment by ug93tad** [comment]
Thanks for pointing this out. It's fixed in the latest commit. 

Actually the start_client.sh is deprecated, as the main run script (`run.py`) no longer use it. 

You can use the `start_ycsb_client.sh` instead. Pull the latest version first. 

You also need to go to src/macro/kvstore and run `make`.
